export interface CreatesIssuesFromHierarchizedElementsDsl {
  givenHierarchizedJsonWithTwoTrees(): void;
  whenCreatingGitHubIssues(): Promise<void>;
  thenSevenIssuesCreatedForBranchWithUserStories(): void;
  thenAllIssuesHaveMilestoneMVP(): void;
  thenEachIssueHasCorrectTypeTitleAndElementId(): void;
  thenParentIssuesMirrorHierarchy(): void;
  thenNoIssuesForBranchWithoutUserStories(): void;
  thenRuleIsNotCreatedAsIssue(): void;
  thenIssueBodyMatchesElementBody(): void;
  thenUserStoryBodyContainsRules(): void;
  thenScenariosAreSubissuesOfUserStory(): void;
  thenIssueBodyIsTextAfterTitleWithLineBreaksPreserved(): void;
}

export interface UpdatesExistingIssuesIdempotentlyDsl {
  givenHierarchizedJsonWithTwoTrees(): void;
  whenCreatingGitHubIssuesTwice(): Promise<void>;
  thenSecondCallUpdatesInsteadOfCreating(): void;
  thenNoIssuesAreDuplicated(): void;
}

export interface ScenarioIssueHasTestDriversDsl {
  givenHierarchizedJsonWithScenarioTestDrivers(): void;
  whenCreatingGitHubIssues(): Promise<void>;
  thenScenarioIssueHasTestDrivers(): void;
}

export interface UploadsWireframeAndAddsToBodyDsl {
  givenAUserStoryWithAttachment(): void;
  whenCreatingGitHubIssues(): Promise<void>;
  thenImageIsUploadedAndBodyContainsWireframe(): void;
}

export interface UserStoryIssueBodyContainsBoundedContextDsl {
  givenAUserStoryWithBoundedContext(): void;
  whenCreatingGitHubIssues(): Promise<void>;
  thenIssueBodyContainsBoundedContext(): void;
}

export interface WrapsBodyWithAutoMarkersDsl {
  givenAnAutoGeneratedBody(): void;
  whenWrappingBody(): void;
  thenResultContainsMarkersAndWarning(): void;
}

export interface ExtractsManualContentAfterMarkersDsl {
  givenABodyWithMarkersAndManualContent(): void;
  whenExtractingManualContent(): void;
  thenManualContentIsExtracted(): void;
}

export interface ReturnsEmptyManualContentWhenNoMarkersDsl {
  givenABodyWithoutMarkers(): void;
  whenExtractingManualContent(): void;
  thenManualContentIsEmpty(): void;
}

export interface PreservesManualContentOnUpdateDsl {
  givenAnExistingBodyWithManualContent(): void;
  whenReconstructingWithNewAutoBody(): void;
  thenResultContainsNewAutoAndPreservedManual(): void;
}

export interface DeletesRemovedScenarioOnResyncDsl {
  givenHierarchizedJsonWithUserStoryAndTwoScenarios(): void;
  whenCreatingThenResyncingWithOneScenarioRemoved(): Promise<void>;
  thenRemovedScenarioIsDeleted(): void;
  thenRemainingScenarioIsStillPresent(): void;
}

export interface DeletesRemovedActionOnResyncDsl {
  givenHierarchizedJsonWithImpactAndTwoActions(): void;
  whenCreatingThenResyncingWithOneActionRemoved(): Promise<void>;
  thenRemovedActionIsDeleted(): void;
  thenRemainingActionIsStillPresent(): void;
}
