import { expect } from 'vitest';
import { AutoBodyMarkers } from '../../autoBodyMarkers';
import type {
  WrapsBodyWithAutoMarkersDsl,
  ExtractsManualContentAfterMarkersDsl,
  ReturnsEmptyManualContentWhenNoMarkersDsl,
  PreservesManualContentOnUpdateDsl,
} from '../createGitHubIssues.dsl';

export class WrapsBodyWithAutoMarkersDriver implements WrapsBodyWithAutoMarkersDsl {
  private body = '';
  private result = '';

  givenAnAutoGeneratedBody(): void {
    this.body = 'En tant que PO je veux...\n\n## Règles\n- Règle 1';
  }

  whenWrappingBody(): void {
    this.result = AutoBodyMarkers.wrapAutoBody(this.body);
  }

  thenResultContainsMarkersAndWarning(): void {
    expect(this.result).toContain('<!-- figjam:auto-start -->');
    expect(this.result).toContain('<!-- figjam:auto-end -->');
    expect(this.result).toContain('⚠️ Import automatique depuis FigJam — ne pas modifier cette section');
    expect(this.result).toContain('⚠️ Fin section import automatique');
    expect(this.result).toContain(this.body);
    expect(this.result.endsWith('\n---')).toBe(true);
  }
}

export class ExtractsManualContentAfterMarkersDriver implements ExtractsManualContentAfterMarkersDsl {
  private existingBody = '';
  private result = '';

  givenABodyWithMarkersAndManualContent(): void {
    this.existingBody = [
      '<!-- figjam:auto-start -->',
      '⚠️ Import automatique depuis FigJam — ne pas modifier cette section',
      '',
      'Auto content here',
      '',
      '⚠️ Fin section import automatique',
      '<!-- figjam:auto-end -->',
      '---',
      '',
      '## Notes',
      'Mes notes manuelles',
    ].join('\n');
  }

  whenExtractingManualContent(): void {
    this.result = AutoBodyMarkers.extractManualContent(this.existingBody);
  }

  thenManualContentIsExtracted(): void {
    expect(this.result).toContain('## Notes');
    expect(this.result).toContain('Mes notes manuelles');
  }
}

export class ReturnsEmptyManualContentWhenNoMarkersDriver implements ReturnsEmptyManualContentWhenNoMarkersDsl {
  private existingBody = '';
  private result = '';

  givenABodyWithoutMarkers(): void {
    this.existingBody = 'Old body without markers';
  }

  whenExtractingManualContent(): void {
    this.result = AutoBodyMarkers.extractManualContent(this.existingBody);
  }

  thenManualContentIsEmpty(): void {
    expect(this.result).toBe('');
  }
}

export class PreservesManualContentOnUpdateDriver implements PreservesManualContentOnUpdateDsl {
  private existingBody = '';
  private newAutoBody = '';
  private result = '';

  givenAnExistingBodyWithManualContent(): void {
    this.existingBody = [
      '<!-- figjam:auto-start -->',
      '⚠️ Import automatique depuis FigJam — ne pas modifier cette section',
      '',
      'Old auto content',
      '',
      '⚠️ Fin section import automatique',
      '<!-- figjam:auto-end -->',
      '---',
      '',
      '## Notes',
      'Mes notes manuelles',
    ].join('\n');
    this.newAutoBody = 'New auto content updated';
  }

  whenReconstructingWithNewAutoBody(): void {
    const manualContent = AutoBodyMarkers.extractManualContent(this.existingBody);
    const wrappedAuto = AutoBodyMarkers.wrapAutoBody(this.newAutoBody);
    this.result = wrappedAuto + manualContent;
  }

  thenResultContainsNewAutoAndPreservedManual(): void {
    expect(this.result).toContain('New auto content updated');
    expect(this.result).not.toContain('Old auto content');
    expect(this.result).toContain('## Notes');
    expect(this.result).toContain('Mes notes manuelles');
    expect(this.result).toContain('<!-- figjam:auto-start -->');
    expect(this.result).toContain('<!-- figjam:auto-end -->');
  }
}
