import { describe, test } from 'vitest';
import {
  WrapsBodyWithAutoMarkersDriver,
  ExtractsManualContentAfterMarkersDriver,
  ReturnsEmptyManualContentWhenNoMarkersDriver,
  PreservesManualContentOnUpdateDriver,
} from './autoBodyMarkers.useCaseDriver';

describe('Auto body markers', () => {
  test('wraps body with auto markers and warnings', () => {
    const driver = new WrapsBodyWithAutoMarkersDriver();
    driver.givenAnAutoGeneratedBody();
    driver.whenWrappingBody();
    driver.thenResultContainsMarkersAndWarning();
  });

  test('extracts manual content after markers', () => {
    const driver = new ExtractsManualContentAfterMarkersDriver();
    driver.givenABodyWithMarkersAndManualContent();
    driver.whenExtractingManualContent();
    driver.thenManualContentIsExtracted();
  });

  test('returns empty manual content when no markers (retro-compatible)', () => {
    const driver = new ReturnsEmptyManualContentWhenNoMarkersDriver();
    driver.givenABodyWithoutMarkers();
    driver.whenExtractingManualContent();
    driver.thenManualContentIsEmpty();
  });

  test('preserves manual content on update with new auto body', () => {
    const driver = new PreservesManualContentOnUpdateDriver();
    driver.givenAnExistingBodyWithManualContent();
    driver.whenReconstructingWithNewAutoBody();
    driver.thenResultContainsNewAutoAndPreservedManual();
  });
});
